name: Issue to PR

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write # To create branches, commit files
  pull-requests: write # To create PRs
  issues: write # To write issue data

jobs:
  initial_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add initial comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = context.payload.issue.title;
            if (issueTitle.includes('packagefox:')) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: '👋 Thank you for your contribution! This issue needs to be approved by a maintainer before proceeding. A maintainer can approve this issue by commenting `/approve` on this issue.'
              });
            }
